# Generated by Django 3.1.6 on 2021-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='attendance',
            field=models.JSONField(default=list),
        ),
    ]
