# Generated by Django 3.1.6 on 2021-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210905_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_student',
            field=models.JSONField(default=list),
        ),
    ]
